name: Minikube start and deploy

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying minikube
        
    steps:
    
      # Build Steps
      - name: Checkout Code
        uses: actions/checkout@v2    
      - name: Start Minikube
        id: minikube
        uses: hiberbee/github-action-minikube@latest
        with:
          profile: github
          minikube-version: 1.24.0
          addons: default-storageclass,storage-provisioner,ingress
      - name: Run everything
        run: ./build.sh
      - name: testing
        run: kubectl get ingress server-ingress -o yaml
      - name: testing-jsonpath
        run: kubectl get ingress server-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      
      
        
  
    
